name: "release-build"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Clean code
        run: |
          ./gradlew clean

      - name: Check lint
        run: |
          ./gradlew lint

      - name: Check ktlint
        run: |
          ./gradlew ktlintCheck

      - name: Build application
        run: |
          ./gradlew assembleDebug

      - name: Upload APK
        if: ${{ success() }}
        uses: actions/upload-artifact@v2.2.0
        with:
          name: apk-artifact
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2.2.0
        with:
          name: logs-artifact
          path: |
            app/build/reports/ktlint/**/*.xml
            app/build/reports/lint-results.html

  submit-artifact:
    runs-on: ubuntu-latest
    if: always()
    needs: build-android
    env:
      ARTIFACT_NAME: artifact-master-${{GITHUB_RUN_NUMBER}}.zip
      DOWNLOAD_ARTIFACT_PATH: artifacts/
      ARTIFACT_PATH: artifacts/artifact-master-${{GITHUB_RUN_NUMBER}}.zip
    steps:
      - name: download-apk-artifact
        id: apk
        if: ${{ needs.build-android.result == 'success' }}
        uses: actions/download-artifact@v2.0.5
        with:
          name: apk-artifact
          path: ${{env.DOWNLOAD_ARTIFACT_PATH}}

      - name: download-logs-artifact
        id: logs
        if: ${{ needs.build-android.result != 'success' }}
        uses: actions/download-artifact@v2.0.5
        with:
          name: logs-artifact
          path: ${{env.DOWNLOAD_ARTIFACT_PATH}}

      - name: Compress
        run: ls -R && pwd && zip ${{ env.ARTIFACT_NAME }} . -r
        working-directory: ${{env.DOWNLOAD_ARTIFACT_PATH}}

      - name: Submit
        if: ${{ needs.build-android.result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: Build for branch *master* successful!
          document: ${{ env.ARTIFACT_PATH }}

      - name: Submit
        if: ${{ needs.build-android.result != 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: failed build!
          document: ${{ env.ARTIFACT_PATH }}
